#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamDroid.NavigationDrawer.MvxSample.Droid.Resource", IsApplication=true)]

namespace XamDroid.NavigationDrawer.MvxSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.centered = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.clipPadding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.clipPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fadeDelay = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.fadeDelay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fadeLength = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.fadeLength;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fades = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fillColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.fillColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.footerColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorHeight = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.footerIndicatorHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.footerIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorUnderlinePadding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.footerIndicatorUnderlinePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerLineHeight = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.footerLineHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerPadding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.footerPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.gapWidth = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.gapWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.linePosition = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.linePosition;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.lineWidth = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.lineWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.pageColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.pageColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.radius = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedBold = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.selectedBold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.snap = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.strokeColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.strokeColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.strokeWidth = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.titlePadding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.titlePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.topPadding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.topPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.unselectedColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.unselectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiCirclePageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.vpiCirclePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiIconPageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.vpiIconPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiLinePageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.vpiLinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTabPageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.vpiTabPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTitlePageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.vpiTitlePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiUnderlinePageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Attribute.vpiUnderlinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_centered = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Boolean.default_circle_indicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_snap = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Boolean.default_circle_indicator_snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_line_indicator_centered = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Boolean.default_line_indicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_title_indicator_selected_bold = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Boolean.default_title_indicator_selected_bold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_underline_indicator_fades = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Boolean.default_underline_indicator_fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_fill_color = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.default_circle_indicator_fill_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_page_color = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.default_circle_indicator_page_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_stroke_color = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.default_circle_indicator_stroke_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_selected_color = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.default_line_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_unselected_color = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.default_line_indicator_unselected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_footer_color = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.default_title_indicator_footer_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_selected_color = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.default_title_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_text_color = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.default_title_indicator_text_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_underline_indicator_selected_color = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.default_underline_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_dark = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.vpi__background_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_light = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.vpi__background_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_dark = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_light = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_dark = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.vpi__bright_foreground_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_light = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.vpi__bright_foreground_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_dark = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_light = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__dark_theme = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.vpi__dark_theme;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__light_theme = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Color.vpi__light_theme;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_radius = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_circle_indicator_radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_stroke_width = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_circle_indicator_stroke_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_gap_width = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_line_indicator_gap_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_line_width = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_line_indicator_line_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_stroke_width = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_line_indicator_stroke_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_clip_padding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_title_indicator_clip_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_height = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_title_indicator_footer_indicator_height;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_line_height = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_title_indicator_footer_line_height;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_padding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_title_indicator_footer_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_text_size = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_title_indicator_text_size;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_title_padding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_title_indicator_title_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_top_padding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Dimension.default_title_indicator_top_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_indicator = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Drawable.vpi__tab_indicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_focused_holo = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Drawable.vpi__tab_selected_focused_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_holo = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Drawable.vpi__tab_selected_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_pressed_holo = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Drawable.vpi__tab_selected_pressed_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_focused_holo = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Drawable.vpi__tab_unselected_focused_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_holo = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Drawable.vpi__tab_unselected_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_pressed_holo = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Drawable.vpi__tab_unselected_pressed_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.bottom = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Id.bottom;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.none = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Id.none;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.top = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Id.top;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.triangle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Id.triangle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.underline = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Id.underline;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_circle_indicator_orientation = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Integer.default_circle_indicator_orientation;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_footer_indicator_style = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Integer.default_title_indicator_footer_indicator_style;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_line_position = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Integer.default_title_indicator_line_position;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_delay = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Integer.default_underline_indicator_fade_delay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_length = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Integer.default_underline_indicator_fade_length;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.TextAppearance_TabPageIndicator = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Style.TextAppearance_TabPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Theme_PageIndicatorDefaults = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Style.Theme_PageIndicatorDefaults;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Style.Widget;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget_IconPageIndicator = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Style.Widget_IconPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget_TabPageIndicator = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Style.Widget_TabPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.CirclePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_background = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.CirclePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_orientation = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.CirclePageIndicator_android_orientation;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_centered = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.CirclePageIndicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_fillColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.CirclePageIndicator_fillColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_pageColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.CirclePageIndicator_pageColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_radius = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.CirclePageIndicator_radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_snap = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.CirclePageIndicator_snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.CirclePageIndicator_strokeColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeWidth = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.CirclePageIndicator_strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.LinePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_android_background = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.LinePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_centered = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.LinePageIndicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_gapWidth = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.LinePageIndicator_gapWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_lineWidth = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.LinePageIndicator_lineWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_selectedColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.LinePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_strokeWidth = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.LinePageIndicator_strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_unselectedColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.LinePageIndicator_unselectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_background = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_android_textColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textSize = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_android_textSize;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_clipPadding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_clipPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_footerColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerLineHeight = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_footerLineHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerPadding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_footerPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_linePosition = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_linePosition;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedBold = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_selectedBold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_titlePadding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_titlePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_topPadding = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.TitlePageIndicator_topPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.UnderlinePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_android_background = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.UnderlinePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeDelay = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.UnderlinePageIndicator_fadeDelay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeLength = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.UnderlinePageIndicator_fadeLength;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fades = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.UnderlinePageIndicator_fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_selectedColor = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.UnderlinePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.ViewPagerIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = global::XamDroid.NavigationDrawer.MvxSample.Droid.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int standard_background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_card = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_card_inverse = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drawer_shadow_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int drawer_shadow_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_drawer_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_drawer_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splash = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MvxBindingTagUnique = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int content_frame = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int drawer_layout = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int left_drawer = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int viewPager = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int viewPagerIndicator = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int item_columns = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_browse = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_friends = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_friends_all = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_profile = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragments_friends_recent = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int item_menu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int item_monkey = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int page_friend = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int page_home_view = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SplashScreen = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int drawer_close = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int drawer_open = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int MyBaseTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int MyTheme = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int Theme_Splash = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
